import {useId} from 'react';
import type {AshComponent} from './data/types';
import {longitudeIntervals} from './lib/section';
export function AltitudeSection({records,latitude,onLatitude}:{records:AshComponent[];latitude:number;onLatitude:(latitude:number)=>void}){
 const titleId=useId(),descriptionId=useId();
 const slices=records.flatMap(c=>longitudeIntervals(c.coordinates,latitude).map(([west,east])=>({component:c,west,east})));
 const points=records.flatMap(c=>c.coordinates);const west=points.length?Math.min(...points.map(p=>p[0])):100,east=points.length?Math.max(...points.map(p=>p[0])):110;
 const span=Math.max(.1,east-west),maxFL=Math.max(100,Math.ceil(Math.max(0,...records.map(c=>c.upper))/100)*100);
 const x=(lon:number)=>75+(lon-west)/span*790,y=(fl:number)=>230-fl/maxFL*195;
 return <section className="altitude-section"><div className="section-heading"><div><div className="eyebrow">A SLICE THROUGH THE SELECTED POLYGONS</div><h2>Where the altitude bands overlap.</h2><p>An east–west cross-section at {Math.abs(latitude).toFixed(2)}°{latitude<0?'S':'N'}. Each box intersects one advisory polygon at this latitude and retains its reported lower and upper flight levels.</p></div><label>Transect latitude<input aria-label="Cross-section latitude" type="range" min="-25" max="10" step="0.01" value={latitude} onChange={e=>onLatitude(Number(e.target.value))}/><output>{Math.abs(latitude).toFixed(2)}°{latitude<0?'S':'N'}</output></label></div>
 <svg viewBox="0 0 900 290" role="img" aria-labelledby={`${titleId} ${descriptionId}`}><title id={titleId}>East–west ash altitude cross-section</title><desc id={descriptionId}>{slices.length} intersecting altitude ranges at latitude {latitude}. Horizontal axis is longitude; vertical axis is reported flight level. Boxes represent advisory bounds, not measured ash distribution within them.</desc>{Array.from({length:maxFL/100+1},(_,i)=>i*100).map(fl=><g key={fl}><line x1="75" x2="865" y1={y(fl)} y2={y(fl)} stroke="currentColor" opacity=".17"/><text x="63" y={y(fl)+4} textAnchor="end">{fl===0?'SFC*':`FL${fl}`}</text></g>)}{Array.from({length:6},(_,i)=>west+span*i/5).map(lon=><g key={lon}><line x1={x(lon)} x2={x(lon)} y1="35" y2="230" stroke="currentColor" opacity=".1"/><text x={x(lon)} y="253" textAnchor="middle">{lon.toFixed(1)}°E</text></g>)}{slices.map((slice,i)=><g key={`${slice.component.id}-${i}`}><rect className={`section-range ${slice.component.kind}`} x={x(slice.west)} y={y(slice.component.upper)} width={Math.max(1,x(slice.east)-x(slice.west))} height={y(slice.component.lower)-y(slice.component.upper)}><title>{slice.component.kind}: {slice.component.lower===0?'SFC':`FL${slice.component.lower}`}–FL{slice.component.upper}; {slice.west.toFixed(2)}–{slice.east.toFixed(2)}°E</title></rect></g>)}<text x="470" y="280" textAnchor="middle">Longitude · west → east</text></svg>
 <p className="section-status" role="status">{slices.length?`${slices.length} intersecting altitude ranges. Solid orange: observed; dotted purple: estimated; dashed gold: forecast.`:'This latitude does not intersect any selected polygon. Move the transect or change the altitude filter.'}</p><p className="section-caveat">Flight levels describe pressure-altitude bands, not exact heights above the ground. *SFC is drawn at the baseline schematically; terrain is not modelled. No concentration or continuous filling of these boxes is implied.</p>
 </section>;
}
