import {useEffect,useMemo,useState} from 'react';
import {MapView} from './Map';
import {assetUrl} from './lib/assets';
import type {AshComponent} from './data/types';
type Entry={id:string;name:string;classification:'A'|'B'|'C';coordinates:[number,number];region:string;submarine:boolean;advisoryId:string|null};
type DirectoryData={sourceUrl:string;sourceUpdatedAt:string;retrievedAt:string;provider:string;coverage:string;definitions:Record<'A'|'B'|'C',string>;volcanoes:Entry[]};
const bounds:[number,number,number,number]=[94,-11,142,7];
const noAsh:AshComponent[]=[];
export function Directory({onExplore}:{onExplore:(id:string)=>void}){
 const [data,setData]=useState<DirectoryData|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(assetUrl('/data/directory.json'),{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Could not load the volcano directory.');return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 return data?<DirectoryLoaded data={data} onExplore={onExplore}/>:<p role="status">{error||'Loading Indonesia’s volcano directory…'}</p>;
}
function DirectoryLoaded({data,onExplore}:{data:DirectoryData;onExplore:(id:string)=>void}){
 const [query]=useState(()=>new URLSearchParams(location.search));
 const [search,setSearch]=useState(query.get('directorySearch')??''),[kind,setKind]=useState(['A','B','C'].includes(query.get('directoryType')??'')?query.get('directoryType')!:'all'),[region,setRegion]=useState(data.volcanoes.some(v=>v.region===query.get('directoryRegion'))?query.get('directoryRegion')!:'all'),[selected,setSelected]=useState(query.get('directoryVolcano')??'');
 const visible=useMemo(()=>data.volcanoes.filter(v=>(kind==='all'||v.classification===kind)&&(region==='all'||v.region===region)&&`${v.name} ${v.region}`.toLowerCase().includes(search.toLowerCase().trim())),[data,search,kind,region]);
 const current=visible.find(v=>v.id===selected);
 useEffect(()=>{const p=new URLSearchParams(location.search);for(const [key,value] of Object.entries({directorySearch:search,directoryType:kind==='all'?'':kind,directoryRegion:region==='all'?'':region,directoryVolcano:current?.id??''})){if(value)p.set(key,value);else p.delete(key);}history.replaceState(null,'',`?${p}`);},[search,kind,region,current?.id]);
 return <section className="directory"><div className="eyebrow">05 / INDONESIA’S VOLCANO DIRECTORY</div><h1>Along the Ring of Fire.</h1><p className="standfirst">Explore Indonesia’s 127 volcanoes in the official MAGMA classification table, from Sumatra through Java and Nusa Tenggara to Sulawesi and Maluku.</p>
 <div className="directory-types">{(['A','B','C'] as const).map(type=><button key={type} className={`type-${type}`} aria-pressed={kind===type} onClick={()=>{setKind(kind===type?'all':type);setSelected('');}}><span>TYPE {type}</span><strong>{data.volcanoes.filter(v=>v.classification===type).length}</strong><p>{data.definitions[type]}</p></button>)}</div>
 <p className="directory-context">These are official volcano types, not “erupting now” or “safe” labels. MAGMA includes all three types in its active-volcano inventory; Type B and C do not mean extinct. <a href={data.sourceUrl} target="_blank" rel="noreferrer">Classification table · updated 20 September 2021 ↗</a></p>
 <div className="directory-filters"><label>Find a volcano<input type="search" value={search} placeholder="Try Merapi, Ibu or Sumatera" onChange={e=>{setSearch(e.target.value);setSelected('');}}/></label><label>Region<select aria-label="Region" value={region} onChange={e=>{setRegion(e.target.value);setSelected('');}}><option value="all">All regions</option>{[...new Set(data.volcanoes.map(v=>v.region))].sort().map(r=><option key={r}>{r}</option>)}</select></label><label>Classification<select aria-label="Classification" value={kind} onChange={e=>{setKind(e.target.value);setSelected('');}}><option value="all">All types</option>{['A','B','C'].map(t=><option value={t} key={t}>Type {t}</option>)}</select></label><button onClick={()=>{setSearch('');setKind('all');setRegion('all');setSelected('');}}>Reset filters</button></div>
 <div className="directory-map map-card"><MapView records={noAsh} volcanoes={visible} selectedId={current?.id??''} eventBounds={bounds} onSelectVolcano={setSelected}/><div className="map-location"><span>OFFICIAL CLASSIFICATIONS / SOURCE SNAPSHOT</span><strong>{current?current.name:'Indonesia’s volcanic arc'}</strong></div><div className="map-legend"><span className="type-A">▲ Type A</span><span className="type-B">▲ Type B</span><span className="type-C">▲ Type C</span></div><div className="map-credit">PVMBG / MAGMA Indonesia · Natural Earth</div></div>
 {current&&<aside className="directory-selection" aria-live="polite"><div><span className={`type-${current.classification}`}>TYPE {current.classification}</span><h2>{current.name}</h2><p>{current.region}{current.submarine?' · Submarine volcano':''} · {data.definitions[current.classification]}</p></div>{current.advisoryId&&<button onClick={()=>onExplore(current.advisoryId!)}>Explore ash advisories ↗</button>}<button aria-label="Close selected volcano" onClick={()=>setSelected('')}>×</button></aside>}
 <p className="directory-results" role="status">Showing {visible.length} of {data.volcanoes.length} volcanoes</p>
 {visible.length?<div className="directory-list">{visible.map(v=><button key={v.id} className={`directory-entry ${selected===v.id?'selected':''}`} onClick={()=>setSelected(v.id)} aria-pressed={selected===v.id}><span className={`type-badge type-${v.classification}`}>Type {v.classification}</span><strong>{v.name}</strong><small>{v.region}{v.submarine?' · Submarine':''}</small></button>)}</div>:<p>No volcanoes match these filters. Try another name or reset the filters.</p>}
 <details className="directory-source"><summary>Coverage, classifications and source date</summary><p>{data.coverage} Coordinates and classifications come directly from PVMBG’s table; no category is inferred from missing eruption reports. “BL” denotes a submarine volcano.</p><p>The source was updated on 20 September 2021 and retrieved on {data.retrievedAt}. Badan Geologi’s July 2026 summary and BNPB’s December 2020 report both give 77 A, 29 B and 21 C. These totals differ from the table’s 76 A, 30 B and 21 C, but do not identify a named reclassification. This page preserves the table’s individual labels; its update date alone does not establish when each classification was reviewed.</p><a href="https://geologi.esdm.go.id/index.php/media-center/belajar-hidup-berdampingan-dengan-bencana-strategi-siaga-di-daerah-cincin-api" target="_blank" rel="noreferrer">Badan Geologi’s 2026 summary ↗</a> · <a href="https://www.bnpb.go.id/index.php/berita/erupsi-gunung-ili-lewotolok-paling-signifikan-di-tahun-2020" target="_blank" rel="noreferrer">BNPB’s 2020 report ↗</a><p><a href={data.sourceUrl} target="_blank" rel="noreferrer">Read the complete source table ↗</a> · <a href={assetUrl('/data/directory.json')} download>Download this directory ↓</a></p></details>
 </section>;
}
