import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapView} from './Map';
import {AltitudeSection} from './AltitudeSection';
import {SatelliteComparison} from './SatelliteComparison';
import {Directory} from './Directory';
import {EventReplay} from './EventReplay';
import {MeasurementGuide} from './MeasurementGuide';
import {type Catalog,type Product,type Volcano,type AshComponent,editions,displayDate,initialPositionLabel} from './data/types';
import './real.css';
import {assetUrl} from './lib/assets';
type View='explorer'|'story'|'compare'|'replay'|'directory';
const query=new URLSearchParams(location.search);
function App(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();Promise.all(['/data/catalog.json','/data/imagery.json'].map(url=>fetch(assetUrl(url),{signal:controller.signal}).then(r=>{if(!r.ok)throw Error(`Data request failed (${r.status})`);return r.json();}))).then(([data,imagery])=>setCatalog({...data,imagery:imagery.frames})).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 return catalog?<Experience catalog={catalog}/>:<div className="loading" role="status">{error||'Loading the source-backed advisory archive…'}</div>;
}
function Experience({catalog}:{catalog:Catalog}){
 const [view,setView]=useState<View>(['explorer','story','compare','replay','directory'].includes(query.get('view')??'')?query.get('view') as View:'explorer');
 const [threeD,setThreeD]=useState(query.get('dimension')==='3d');
 const requestedReplayTime=Number(query.get('time'));
 const [replayTime,setReplayTime]=useState(query.has('time')&&Number.isFinite(requestedReplayTime)&&requestedReplayTime>=Date.parse('2026-09-04T15:00:00Z')&&requestedReplayTime<=Date.parse('2026-09-08T17:00:00Z')?requestedReplayTime:catalog.volcanoes.find(v=>v.id==='262000')!.window.preferredStart!);
 const [volcanoId,setVolcanoId]=useState(catalog.volcanoes.some(v=>v.id===query.get('volcano'))?query.get('volcano')!:'262000');
 const [eventId,setEventId]=useState(query.get('event')??catalog.events.find(e=>catalog.products.some(p=>p.id===query.get('edition')&&p.volcanoId===e.volcanoId&&p.issuedAt>=e.start&&p.issuedAt<=e.end))?.id??'');
 const events=catalog.events.filter(e=>e.volcanoId===volcanoId);const selectedEvent=events.find(e=>e.id===eventId)??events[0];
 const products=useMemo(()=>editions(catalog,volcanoId,selectedEvent.id),[catalog,volcanoId,selectedEvent.id]);
 const [productId,setProductId]=useState(query.get('edition')??'');const product=products.find(p=>p.id===productId)??products[0];
 const [lead,setLead]=useState([0,6,12,18].includes(Number(query.get('lead')))?Number(query.get('lead')):0),[band,setBand]=useState(['all','0-100','100-200','200-500','500-600'].includes(query.get('band')??'')?query.get('band')!:'all'),[playing,setPlaying]=useState(false),[local,setLocal]=useState(query.get('local')==='1'),[method,setMethod]=useState(false),[copied,setCopied]=useState(false),[satellite,setSatellite]=useState(query.get('satellite')==='1');
 const [sectionLatitude,setSectionLatitude]=useState<number|null>(null);
 const volcano=catalog.volcanoes.find(v=>v.id===volcanoId)!;
 const raster=catalog.imagery.find(r=>r.volcanoId===volcanoId&&r.date===new Date(product.issuedAt).toISOString().slice(0,10));
 const zone=local?volcano.timeZone:'UTC';const index=products.indexOf(product);
 const records=product.components.filter(c=>c.leadHours===lead&&(band==='all'||(c.lower<Number(band.split('-')[1])&&c.upper>Number(band.split('-')[0]))));
 const chooseVolcano=(id:string)=>{setPlaying(false);setVolcanoId(id);setProductId('');setSectionLatitude(null);setEventId('');};
 const step=(n:number)=>{setPlaying(false);setProductId(products[Math.max(0,Math.min(products.length-1,index+n))].id);};
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>{const next=products[index+1];if(next)setProductId(next.id);else setPlaying(false);},1500);return()=>clearInterval(t);},[playing,index,products]);
 useEffect(()=>{const p=new URLSearchParams(location.search);Object.entries({view,event:selectedEvent.id,dimension:threeD?'3d':'2d',volcano:volcanoId,edition:product.id,lead:String(lead),band,satellite:satellite?'1':'0',local:local?'1':'0'}).forEach(([key,value])=>p.set(key,value));if(view==='replay')p.set('time',String(replayTime));if(query.get('embed')==='1')p.set('embed','1');history.replaceState(null,'',`?${p}`);},[view,volcanoId,product.id,lead,band,satellite,local,replayTime,threeD,selectedEvent.id]);
 const share=async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setCopied(false);}};
 return <main className={`app ${view==='story'?'paper':''} ${query.get('embed')==='1'?'embedded':''}`}>
  <header className="masthead"><a href="https://caleb-tutty.com" className="wordmark">Caleb Tutty<span>FIELD NOTES / INDONESIA</span></a><span className="project-name">An archipelago of ash</span><button onClick={share}>{copied?'Link copied ✓':'Share view ↗'}</button></header>
  <nav className="view-tabs" aria-label="Presentation options">{([['explorer','01','Advisory explorer'],['story','02','Editorial story'],['compare','03','Volcano comparison'],['replay','04','Event replay'],['directory','05','All volcanoes']] as const).map(([key,num,label])=><button key={key} aria-pressed={view===key} onClick={()=>{setPlaying(false);setView(key);}}><span>{num}</span>{label}</button>)}<button className="method-button" onClick={()=>setMethod(true)}>Sources & method ↗</button></nav>
  <div className="archive-note"><i/>{view==='directory'?'PVMBG CLASSIFICATION TABLE':'REAL ADVISORY DATA'}<span>{view==='directory'?'127 entries · source updated September 2021 · not live alert levels':view==='replay'?'4–8 September event imagery and reports · retrospective reconstruction':catalog.coverage}</span></div>
  {view==='explorer'&&<>
   <div className="explorer-intro"><div><div className="eyebrow">FROM A SOURCE MESSAGE TO A MAP</div><h1>Where did the ash go?</h1><p>Explore an advisory edition, then compare its observed or estimated position with its forecasts.</p></div><label>VOLCANO<select aria-label="Volcano" value={volcanoId} onChange={e=>chooseVolcano(e.target.value)}>{catalog.volcanoes.map(v=><option key={v.id} value={v.id}>{v.name} · {v.region}</option>)}</select></label></div>
   {events.length>1&&<label className="event-selector">Event window<select aria-label="Event window" value={selectedEvent.id} onChange={e=>{setPlaying(false);setEventId(e.target.value);setProductId('');}}>{events.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></label>}<p className="window-note"><strong>{selectedEvent.label} · {displayDate(selectedEvent.start,volcano.timeZone)} – {displayDate(selectedEvent.end,volcano.timeZone)} ({volcano.timeZone})</strong><br/>{selectedEvent.notes}</p><div className="map-presentation"><div role="group" aria-label="Map presentation"><button aria-pressed={!threeD} onClick={()=>setThreeD(false)}>2D footprints</button><button aria-pressed={threeD} onClick={()=>setThreeD(true)}>3D altitude bands</button></div>{threeD&&<p role="status">Schematic altitude bands: flight levels are rendered at 30.48 metres per FL, with SFC at a flat baseline. Pressure altitude is not exact height above terrain. These translucent shapes show reported bounds, not measured ash volumes.</p>}</div><section className="explorer-grid">
    <div className="map-card"><MapView extruded={threeD} transectLatitude={sectionLatitude??volcano.coordinates[1]} records={records} raster={satellite?raster:undefined} volcanoes={catalog.volcanoes} selectedId={volcanoId} onSelectVolcano={chooseVolcano}/><div className="map-location"><span>{volcano.region.toUpperCase()}</span><strong>{volcano.name}</strong></div><MapLegend/><div className="map-credit">Darwin VAAC · Natural Earth{satellite?' · NASA GIBS':''}</div>{satellite&&raster&&<div className="raster-badge">VIIRS · {raster.date} UTC day<br/>Daily context · not simultaneous with advisory</div>}</div>
    <aside className="details"><div className="eyebrow">ADVISORY {product.number}</div><h2>{lead?`Forecast +${lead} hours`:initialPositionLabel(product)}</h2><span className={`kind-badge ${lead?'forecast':product.leadStates['0'].status!=='geometry'?'unavailable':product.estimated?'estimated':'observed'}`}>{lead?'FORECAST':product.leadStates['0'].status!=='geometry'?initialPositionLabel(product).toUpperCase():product.estimated?'ESTIMATED · NOT DIRECT OBSERVATION':'OBSERVED'}</span>
     <dl><div><dt>Volcano</dt><dd>{volcano.name}</dd></div><div><dt>Edition issued</dt><dd>{displayDate(product.issuedAt,zone)}</dd></div><div><dt>{lead?'Forecast valid':'Position time'}</dt><dd>{displayDate(product.leadStates[String(lead)].validAt,zone)}</dd></div><div><dt>Timezone</dt><dd>{local?volcano.timeZone:'UTC'}</dd></div><div><dt>Altitude bounds</dt><dd>{records.length?records.map(r=>`${r.lower===0?'SFC':`FL${r.lower}`}–FL${r.upper}`).join(', '):'No geometry in this band'}</dd></div></dl>
     <label className="satellite-toggle"><input type="checkbox" checked={satellite} onChange={e=>setSatellite(e.target.checked)}/> VIIRS daily true-colour context</label>{satellite&&raster&&<p className="imagery-note">{raster.date} daily mosaic. Exact overpass time is unavailable; visible features are not classified as ash. <a href={raster.sourceUrl}>NASA source ↗</a></p>}{satellite&&!raster&&<p className="imagery-note" role="status">No daily satellite image is archived for this advisory date. The satellite layer is empty.</p>}<label className="control-label">ALTITUDE FILTER<select aria-label="Altitude band" value={band} onChange={e=>setBand(e.target.value)}><option value="all">All flight levels</option><option value="0-100">Surface–FL100</option><option value="100-200">FL100–FL200</option><option value="200-500">FL200–FL500</option><option value="500-600">FL500–FL600</option></select></label>
     {!records.length&&<p role="status" className="uncertainty">{product.leadStates[String(lead)].status==='not-identifiable'?'The source reports ash not identifiable in satellite data. This does not establish that ash is absent.':product.leadStates[String(lead)].status==='not-available'?'The source explicitly marks this forecast NOT AVBL. No polygon is supplied.':product.leadStates[String(lead)].status==='no-ash-expected'?'The source forecasts NO VA EXP at this target time. This is a forecast statement, not an observation.':'No polygon overlaps the selected altitude band.'}</p>}
     <div className="source-notes">{product.estimated&&<p>The source labels this position EST. It should not be read as a fresh satellite observation.</p>}{product.flags.cloudObscured&&<p>Cloud obscuration is noted in this advisory.</p>}{product.flags.lowForecastConfidence&&<p>The source reports low confidence in forecast movement.</p>}{product.flags.correction&&<p>This is the corrected edition. Its earlier revision is retained in the source catalog.</p>}<p>Polygons describe horizontal extent and altitude bounds, not measured ash concentration.</p></div>
     <a className="source-link" href={product.sourceUrl} target="_blank" rel="noreferrer">Inspect the official archive ↗</a><button className="text-button" onClick={()=>setMethod(true)}>Extraction & provenance ↗</button>
    </aside>
   </section>
   <AltitudeSection records={records} latitude={sectionLatitude??volcano.coordinates[1]} onLatitude={setSectionLatitude}/>
   <section className="edition-controls"><div className="edition-top"><div><span className="eyebrow">SELECTED ADVISORY EDITION</span><strong>{displayDate(product.issuedAt,zone)} <small>{local?'local time':'UTC'}</small></strong></div><div className="playback"><button aria-label="Previous edition" onClick={()=>step(-1)} disabled={index===0}>←</button><button aria-label={playing?'Pause':'Play editions'} onClick={()=>{if(index===products.length-1)setProductId(products[0].id);setPlaying(!playing);}}>{playing?'Pause':'▶ Play'}</button><button aria-label="Next edition" onClick={()=>step(1)} disabled={index===products.length-1}>→</button></div><label className="timezone"><input type="checkbox" checked={local} onChange={e=>setLocal(e.target.checked)}/>Local time</label></div>
    <input className="edition-slider" aria-label="Advisory edition" type="range" min={0} max={products.length-1} step={1} value={index} onChange={e=>{setPlaying(false);setProductId(products[Number(e.target.value)].id);}}/>
    <div className="edition-labels">{products.map((p,i)=><button key={p.id} className={i===index?'active':''} onClick={()=>{setPlaying(false);setProductId(p.id);}}>{displayDate(p.issuedAt,zone)}<small>#{p.number.split('/')[1]}</small></button>)}</div>
    <div className="forecast-control"><span>WITHIN THIS EDITION</span>{[0,6,12,18].map(n=><button key={n} aria-pressed={lead===n} onClick={()=>setLead(n)}>{n?`+${n}h forecast`:'Initial position'}</button>)}<p>Forecast lead is measured from the position time, not the issue time.</p></div>
   </section>
   <details className="explorer-imagery-comparison"><summary>Compare daily satellite imagery around this episode</summary><SatelliteComparison key={selectedEvent.id} place={volcano.name} frames={catalog.imagery.filter(f=>f.volcanoId===volcanoId&&f.date>=new Date(selectedEvent.start-86400000).toISOString().slice(0,10)&&f.date<=new Date(selectedEvent.end).toISOString().slice(0,10))}/></details>
  </>}
  {view==='directory'&&<Directory onExplore={id=>{chooseVolcano(id);setView('explorer');}}/>}
  {view==='replay'&&<EventReplay catalog={catalog} time={replayTime} onTimeChange={setReplayTime}/>}
  {view==='story'&&<Story catalog={catalog} onExplore={(id)=>{chooseVolcano(id);setView('explorer');}}/>}
  {view==='compare'&&<Compare catalog={catalog} onExplore={(id)=>{chooseVolcano(id);setView('explorer');}}/>}
  <footer><span>Source-backed prototypes for caleb-tutty.com</span><a href={assetUrl('/data/catalog.json')} download>Download factual catalog ↓</a><span>Exploratory use · not an aviation or public-safety service</span></footer>
  {method&&<Methodology catalog={catalog} close={()=>setMethod(false)}/>}
 </main>;
}
function MapLegend(){return <div className="map-legend"><span><i className="observed"/>Observed</span><span><i className="estimated"/>Estimated</span><span><i className="forecast"/>Forecast</span></div>;}
function Footprint({product}:{product:Product}){
 const parts=product.components;if(!parts.length)return <div className="footprint" role="img" aria-label="No ash geometry supplied in this edition">No polygon supplied</div>;const points=parts.flatMap(p=>p.coordinates);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2;
 // Every thumbnail uses the same approximate km scale, corrected for latitude.
 const project=([x,y]:number[])=>`${150+(x-cx)*111*Math.cos(cy*Math.PI/180)*1.1},${100-(y-cy)*111*1.1}`;
 return <svg viewBox="0 0 300 200" className="footprint" role="img" aria-label="Initial and forecast ash footprints at a common approximate kilometre scale"><path d="M0 100H300M150 0V200" stroke="currentColor" opacity=".12"/>{parts.map(p=><polygon key={p.id} points={p.coordinates.map(project).join(' ')} fill={p.leadHours?'#c9aa6922':'#b298bf44'} stroke={p.leadHours?'#b79550':p.kind==='observed'?'#c7754b':'#a588b4'} strokeWidth="1.4" strokeDasharray={p.leadHours?'5 4':p.kind==='estimated'?'2 3':undefined}/>)}<path d="M20 180h55m-55-3v6m55-6v6" stroke="currentColor"/><text x="20" y="173" fontSize="9" fill="currentColor">50 km</text></svg>;
}
function Compare({catalog,onExplore}:{catalog:Catalog;onExplore:(id:string)=>void}){
 return <section className="comparison"><div className="eyebrow">OPTION 03 / SMALL MULTIPLES</div><h1>{catalog.volcanoes.length} volcanoes.<br/>Different ash histories.</h1><p className="standfirst">The latest available edition for each volcano in this archived sample. These reports have different issue times; they are not a simultaneous snapshot.</p><div className="comparison-grid">{catalog.volcanoes.map(v=>{const list=editions(catalog,v.id);const p=list[list.length-1];return <article className="volcano-card" key={v.id}><div className="eyebrow">{v.region}</div><h2>{v.name}</h2><Footprint product={p}/><div className="card-stat"><strong>{p.components.length?`FL${Math.max(...p.components.map(c=>c.upper))}`:'No geometry'}</strong><span>{p.components.length?<>highest bound in edition<br/>not summit elevation</>:'No altitude bound supplied'}</span></div><p>{displayDate(p.issuedAt)} UTC<br/>{initialPositionLabel(p)} · {list.length} archived editions</p><button onClick={()=>onExplore(v.id)}>Explore the editions ↗</button></article>;})}</div><div className="comparison-notes"><MapLegend/><p>Each thumbnail uses the same approximate kilometre scale and includes the initial position plus +6, +12 and +18 hour forecasts from one edition. Overlapping outlines are separate forecast times, not accumulated ashfall.</p></div><SourceTable catalog={catalog}/></section>;
}
function Story({catalog,onExplore}:{catalog:Catalog;onExplore:(id:string)=>void}){
 const [chapter,setChapter]=useState(0);
 const earlier=catalog.imagery.filter(r=>r.volcanoId==='262000'&&r.date<'2026-09-08');
 const krakatau=editions(catalog,'262000'),dukono=editions(catalog,'268010');
 const chapters=[{eyebrow:'01 / START WITH THE OBSERVATION',title:'A plume is a moving observation.',body:'A volcanic ash advisory turns an atmospheric observation into a dated outline. In this Krakatau edition, the initial position is labelled OBS. Choose a forecast to see what the same advisory expected six, twelve or eighteen hours later.',product:krakatau.find(p=>!p.estimated)??krakatau[0],lead:0},
 {eyebrow:'02 / LOOK FOR THE QUALIFIER',title:'An estimate needs a different line.',body:'A later Krakatau report labels the position EST. The outline is still useful evidence, but it is not a new direct observation. The map uses a dotted purple boundary so that changing confidence is visible alongside changing shape.',product:krakatau.find(p=>p.estimated)!,lead:0},
 {eyebrow:'03 / READ THE FORECAST CLOCK',title:'The future belongs to an edition.',body:'This +18 hour outline was issued as part of the selected advisory. It is a forecast for a specific timestamp, not a measured path or a prediction generated by this website. Switching reports can change that forecast.',product:krakatau[0],lead:18},
 {eyebrow:'04 / WIDEN THE MAP',title:'The story extends across Indonesia.',body:'The archive also contains Merapi, Semeru, Lewotolok, Ibu and Dukono. Compare their report editions to see different plume directions and altitude bounds. Availability in this small archive is not a ranking of volcanic activity.',product:dukono.find(p=>!p.estimated)??dukono[0],lead:0}];
 const current=chapters[chapter];const v=catalog.volcanoes.find(v=>v.id===current.product.volcanoId)!;
 return <article className="story"><div className="story-title"><div className="eyebrow">MAPS / INDONESIA / A WORKING VISUAL ESSAY</div><h1>An archipelago<br/>of <em>ash.</em></h1><p>Reading the sky through the observations, estimates and forecasts inside volcanic ash advisories.</p><span className="byline">Caleb Tutty · source snapshot 12 September 2026</span></div><div className="story-layout"><div className="story-copy"><div className="eyebrow">{current.eyebrow}</div><h2>{current.title}</h2><p>{current.body}</p><div className="chapter-buttons">{chapters.map((_,i)=><button key={i} aria-label={`Chapter ${i+1}`} aria-pressed={chapter===i} onClick={()=>setChapter(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><button className="story-explore" onClick={()=>onExplore(v.id)}>Open {v.name} in the explorer ↗</button></div><figure><div className="story-map"><MapView records={current.product.components.filter(c=>c.leadHours===current.lead)} volcanoes={catalog.volcanoes} selectedId={v.id} light/><MapLegend/></div><figcaption>{v.name} · {current.lead?`+${current.lead}h forecast`:current.product.estimated?'Estimated position':'Observed position'} · position valid {displayDate(current.product.components.find(c=>c.leadHours===current.lead)!.validAt)} UTC. <a href={current.product.sourceUrl}>Darwin VAAC #{current.product.number} ↗</a></figcaption></figure></div><SatelliteComparison frames={earlier}/><MeasurementGuide/><div className="essay-note"><h3>What this map cannot tell us</h3><p>An advisory outline does not measure ash concentration or establish ground-level exposure. Cloud cover can obscure the satellite view. This is a selected archive, and gaps in it do not mean that a volcano was quiet. The daily satellite mosaics provide context, but their exact overpass times have not been matched to the advisory observations.</p></div></article>;
}
function SourceTable({catalog}:{catalog:Catalog}){return <details className="source-table"><summary>Inspect the archived editions ({catalog.products.length}, including corrections)</summary><div className="table-scroll"><table><thead><tr><th>Volcano</th><th>Advisory</th><th>Issued UTC</th><th>Position type</th><th>Revision</th></tr></thead><tbody>{catalog.products.map(p=><tr key={p.id}><td>{catalog.volcanoes.find(v=>v.id===p.volcanoId)!.name}</td><td><a href={p.sourceUrl}>{p.number} ↗</a></td><td>{displayDate(p.issuedAt)}</td><td>{initialPositionLabel(p)}</td><td>{p.supersededBy?'Superseded':p.flags.correction?'Corrected':'Current in archive'}</td></tr>)}</tbody></table></div></details>;}
function Methodology({catalog,close}:{catalog:Catalog;close:()=>void}){
 const ref=React.useRef<HTMLDialogElement>(null);useEffect(()=>{const trigger=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();trigger?.focus();};},[]);
 return <dialog ref={ref} onCancel={close} aria-labelledby="methodology-title"><button className="dialog-close" onClick={close} aria-label="Close methodology">×</button><div className="eyebrow">SOURCE NOTES</div><h2 id="methodology-title">Real geometry.<br/>Explicit limits.</h2><p>These {catalog.products.length} editions and {catalog.products.reduce((n,p)=>n+p.components.length,0)} geometries come from the Darwin VAAC archive, retrieved {catalog.retrievedAt}. Latitude/longitude in degrees and minutes are converted to GeoJSON; polygons are closed without smoothing or interpolation.</p><p>The Anak Krakatau sample begins on 5 September at 13:30 WIB. Other volcanoes have independent archive windows; those start dates are not verified eruption onsets. Estimated positions remain distinct from observations; forecast times come directly from each product. Corrected editions supersede older revisions in the explorer, while the catalog retains both.</p><p>The inputs preserve a factual extract from the BOM archive and Darwin messages mirrored by GDACS. Repeated continuation suffixes in the GDACS HTML are removed during parsing. Duplicate editions prefer the BOM extract; source links and input checksums are retained.</p><p>Natural Earth v5.1.2 supplies public-domain coastlines. NASA GIBS supplies dated VIIRS true-colour daily mosaics with preserved request URLs and checksums. Their day-level timestamps must not be treated as coincident with advisory times. The event replay adds ten-minute infrared imagery and retrospective airport evidence from official reports. Scheduled closures and reported reopening times remain distinct; missing evidence stays unknown.</p><p>The publication data gate remains open: archive completeness, earlier morning advisories and reuse terms still need review before a complete event reconstruction is published.</p><a href={catalog.sourceUrl}>Official advisory archive ↗</a><br/><a href={assetUrl('/data/catalog.json')} download>Download the processed catalog ↓</a><SourceTable catalog={catalog}/></dialog>;
}
createRoot(document.getElementById('root')!).render(<App/>);
