import {useState} from 'react';
import type {RasterFrame} from './data/types';
import {assetUrl} from './lib/assets';
type Mode='single'|'swipe'|'split';
export function SatelliteComparison({frames,place='the Sunda Strait'}:{frames:RasterFrame[];place?:string}){
 const [mode,setMode]=useState<Mode>('single'),[leftDate,setLeftDate]=useState(frames[0]?.date??''),[rightDate,setRightDate]=useState(frames.at(-1)?.date??''),[position,setPosition]=useState(50);
 const left=frames.find(f=>f.date===leftDate),right=frames.find(f=>f.date===rightDate);
 if(!left||!right)return <p role="status">No daily satellite images are archived for this episode.</p>;
 const aligned=left.crs===right.crs&&left.bounds.every((b,i)=>b===right.bounds[i]);
 const label=(frame:RasterFrame)=>`${frame.date} UTC day`;
 const source=(frame:RasterFrame)=><a href={frame.sourceUrl} target="_blank" rel="noreferrer">{frame.date} source image ↗</a>;
 return <section className={`satellite-essay satellite-comparison mode-${mode}`}><div className="satellite-copy"><div className="eyebrow">SATELLITE CONTEXT / {frames[0].date} – {frames.at(-1)!.date}</div><h2>{frames.length} days over<br/>{place}.</h2><p>Compare real VIIRS true-colour daily mosaics over the same area. Clouds and haze can resemble or obscure volcanic material; these images alone do not establish ash extent.</p><div className="comparison-modes" role="group" aria-label="Satellite presentation">{(['single','swipe','split'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='single'?'One image':m==='swipe'?'Swipe comparison':'Side by side'}</button>)}</div>
 {mode==='single'?<div className="chapter-buttons">{frames.map(f=><button key={f.id} aria-pressed={f.date===leftDate} onClick={()=>setLeftDate(f.date)}>{new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short'}).format(new Date(f.date))}</button>)}</div>:<div className="satellite-date-controls"><label>Left image<select aria-label="Left satellite date" value={leftDate} onChange={e=>setLeftDate(e.target.value)}>{frames.map(f=><option key={f.id} value={f.date}>{label(f)}</option>)}</select></label><label>Right image<select aria-label="Right satellite date" value={rightDate} onChange={e=>setRightDate(e.target.value)}>{frames.map(f=><option key={f.id} value={f.date}>{label(f)}</option>)}</select></label><button onClick={()=>{setLeftDate(rightDate);setRightDate(leftDate);}}>Swap dates</button></div>}
 <p className="satellite-precision">Daily mosaics combine observations within a UTC day. Exact overpass times have not been matched to the advisory clock.</p></div>
 <figure className="satellite-comparison-figure">{mode==='single'?<SatelliteImage key={left.id} frame={left} place={place}/>:mode==='split'?<div className="satellite-split"><div><span>{label(left)}</span><SatelliteImage key={left.id} frame={left} place={place}/></div><div><span>{label(right)}</span><SatelliteImage key={right.id} frame={right} place={place}/></div></div>:aligned?<><div className="satellite-swipe" onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect();setPosition(Math.round(Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100))));}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const rect=e.currentTarget.getBoundingClientRect();setPosition(Math.round(Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100))));}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}><div className="swipe-image"><SatelliteImage key={right.id} frame={right} place={place}/></div><div className="swipe-image swipe-left" style={{clipPath:`inset(0 ${100-position}% 0 0)`}}><SatelliteImage key={left.id} frame={left} place={place}/></div><span className="swipe-date left">{label(left)}</span><span className="swipe-date right">{label(right)}</span><div className="swipe-divider" style={{left:`${position}%`}} aria-hidden="true"><span>↔</span></div></div><label className="swipe-control">Reveal left image · {position}%<input aria-label="Satellite comparison divider" type="range" min="0" max="100" step="1" value={position} onChange={e=>setPosition(Number(e.target.value))} aria-valuetext={`${position}% left image, ${100-position}% right image`}/></label></>:<p role="status">These images have different geographic extents or projections. Choose side by side to compare them without implying alignment.</p>}
 <figcaption>NASA GIBS / Suomi NPP VIIRS · {mode==='single'?label(left):'Both images use UTC-day timestamps.'} {source(left)}{mode!=='single'&&left.id!==right.id&&<> · {source(right)}</>}{mode!=='single'&&left.id===right.id&&<strong> · Same date selected on both sides.</strong>}<br/>{aligned?'Same geographic extent and projection; north is up.':'Geographic extents differ.'}</figcaption></figure>
 </section>;
}
function SatelliteImage({frame,place}:{frame:RasterFrame;place:string}){
 const [failed,setFailed]=useState(false);
 return failed?<div className="satellite-unavailable" role="status">Image unavailable for {frame.date}. Use its source link below.</div>:<img src={assetUrl(frame.url)} alt={`VIIRS daily true-colour image of ${place} for ${frame.date}`} loading="lazy" draggable={false} onError={()=>setFailed(true)}/>;
}
