import {test,expect} from '@playwright/test';
test('all blog embeds load assets from the mounted subpath and retain working controls',async({page})=>{
 const errors:string[]=[];const requests:string[]=[];const failures:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin==='http://127.0.0.1:4181')requests.push(new URL(r.url()).pathname);});page.on('response',r=>{if(r.status()>=400&&new URL(r.url()).origin==='http://127.0.0.1:4181')failures.push(r.url());});
 await page.goto('/article.html');const app=page.frameLocator('iframe');
 await expect(app.getByRole('heading',{name:'An archipelago of ash.'})).toBeVisible();await expect(app.locator('.masthead')).toBeHidden();await expect(app.locator('.view-tabs')).toBeHidden();
 await expect(app.locator('.volcano-marker').first()).toBeVisible();
 await app.getByRole('button',{name:'Swipe comparison',exact:true}).click();await expect(app.getByRole('slider',{name:'Satellite comparison divider'})).toBeVisible();
 await app.locator('.satellite-swipe').scrollIntoViewIfNeeded();await expect(app.locator('.swipe-left img')).toHaveJSProperty('complete',true);expect(await app.locator('.swipe-left img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(768);
 await page.getByLabel('Presentation').selectOption('explorer');await expect(app.getByRole('heading',{name:'Where did the ash go?'})).toBeVisible();await app.getByLabel('Volcano',{exact:true}).selectOption('268010');await expect(app.locator('.map-location strong')).toHaveText('Dukono');
 await app.getByLabel('Volcano',{exact:true}).selectOption('263300');await app.getByLabel('VIIRS daily true-colour context').check();await expect(app.locator('.real-map')).toHaveAttribute('data-raster-url','/data/imagery/263300-2025-11-19.png');
 await page.getByLabel('Presentation').selectOption('directory');await expect(app.locator('.directory-entry')).toHaveCount(127);await app.getByLabel('Classification',{exact:true}).selectOption('C');await expect(app.locator('.directory-entry')).toHaveCount(21);
 await page.getByLabel('Presentation').selectOption('compare');await expect(app.locator('.volcano-card')).toHaveCount(6);
 await page.getByLabel('Presentation').selectOption('replay');await expect(app.getByLabel('Event time')).toBeVisible();await app.getByLabel('Satellite product',{exact:true}).selectOption('ash');await app.getByRole('button',{name:'Jump to first Ash RGB scan'}).click();await expect(app.locator('.replay-frame-status')).toContainText('Source scan');
 await app.getByLabel('Show comparison pane').check();await expect(app.locator('.replay-panes .real-map')).toHaveCount(2);await expect(app.locator('.replay-panes .real-map').first()).toHaveAttribute('data-raster-url',/ash-rgb/);await expect(app.locator('.replay-panes .real-map').nth(1)).toHaveAttribute('data-raster-url',/himawari/);
 await expect(app.locator('.airport-marker')).toHaveCount(8);
 await app.getByLabel('Inspect airport location').selectOption('halim');
 await expect(app.getByRole('link',{name:'Official location source'})).toHaveAttribute('href','https://hubud.kemenhub.go.id/bandara/122');
 const exportLink=app.getByRole('link',{name:'Inspect event advisory GeoJSON'});
 await expect(exportLink).toHaveAttribute('href','/experiments/volcanoes/data/events/anak-krakatau-2026-09/advisories.geojson');
 const exported=await page.request.get((await exportLink.getAttribute('href'))!);
 expect(exported.ok()).toBe(true);expect((await exported.json()).features).toHaveLength(196);
 await app.getByLabel('Replay altitude band').selectOption('100-200');
 await app.getByLabel('WIB labels').uncheck();
 const replayFrame=page.frames().find(f=>f.url().includes('/experiments/volcanoes/'))!;
 await replayFrame.goto(replayFrame.url());
 await expect(app.getByLabel('Replay altitude band')).toHaveValue('100-200');
 await expect(app.getByLabel('WIB labels')).not.toBeChecked();
 await expect(app.getByLabel('Show comparison pane')).toBeChecked();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const frame=page.frames().find(f=>f.url().includes('/experiments/volcanoes/'))!;expect(await frame.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/blog-embed-mobile.png',fullPage:false});
 expect(errors).toEqual([]);expect(failures).toEqual([]);expect(requests.filter(p=>p!=='/article.html'&&!p.startsWith('/experiments/volcanoes/'))).toEqual([]);
 expect(requests.some(p=>p.includes('maplibre-gl-worker'))).toBe(true);expect(requests).toContain('/experiments/volcanoes/data/land.geojson');
 for(const file of ['event.json','timeline.json','airport-status.json'])expect(requests).toContain(`/experiments/volcanoes/data/events/anak-krakatau-2026-09/${file}`);
 expect(requests).toContain('/experiments/volcanoes/data/imagery/263300-2025-11-19.png');
});
